# Generated by Django 2.0.4 on 2018-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(default='World Cup', max_length=12)),
                ('year', models.IntegerField()),
                ('team', models.CharField(max_length=15)),
                ('PlayerNumber', models.IntegerField()),
                ('position', models.CharField(choices=[('ST', 'ST'), ('RW', 'RW'), ('LW', 'LW'), ('CM', 'CM'), ('DM', 'DM'), ('CB', 'CB'), ('RB', 'RB')], max_length=2)),
                ('fullName', models.CharField(max_length=40)),
                ('club', models.CharField(max_length=40)),
                ('dateOfBirth', models.DateField()),
                ('isCaptain', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
