# Generated by Django 2.0.4 on 2018-04-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0002_auto_20180426_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='club',
            new_name='Club',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='competition',
            new_name='Competition',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='dateOfBirth',
            new_name='DateOfBirth',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='fullName',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isCaptain',
            new_name='IsCaptain',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='NationalTeam',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='Position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year',
        ),
        migrations.AddField(
            model_name='player',
            name='Year',
            field=models.IntegerField(default=2018),
        ),
    ]
