# Generated by Django 2.0.4 on 2018-04-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0003_auto_20180426_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Club',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='FullName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='NationalTeam',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='PlayerNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.CharField(choices=[('ST', 'ST'), ('RW', 'RW'), ('LW', 'LW'), ('CM', 'CM'), ('DM', 'DM'), ('CB', 'CB'), ('RB', 'RB')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Year',
            field=models.IntegerField(default=2018, null=True),
        ),
    ]
