# Generated by Django 2.0.4 on 2018-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0005_auto_20180426_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.CharField(choices=[('ST', 'ST'), ('RW', 'RW'), ('LW', 'LW'), ('CM', 'CM'), ('DM', 'DM'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('FW', 'FW'), ('DF', 'DF')], max_length=2, null=True),
        ),
    ]
