# Generated by Django 2.0.4 on 2018-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0006_auto_20180426_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='DateOfBirth',
            field=models.DateTimeField(null=True),
        ),
    ]
