# Generated by Django 2.0.4 on 2018-04-26 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0007_auto_20180426_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='DateOfBirth',
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
